/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNegociacionesRouteImport } from './routes/_app/negociaciones'
import { Route as AppListasPreciosRouteImport } from './routes/_app/listas-precios'
import { Route as AppHistorialRouteImport } from './routes/_app/historial'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCostosProductosRouteImport } from './routes/_app/costos-productos'
import { Route as AppCostosOperacionalesRouteImport } from './routes/_app/costos-operacionales'
import { Route as AppConfiguracionesRouteImport } from './routes/_app/configuraciones'
import { Route as AppCalculadoraRouteImport } from './routes/_app/calculadora'
import { Route as AppAnalisisVentasRouteImport } from './routes/_app/analisis-ventas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNegociacionesRoute = AppNegociacionesRouteImport.update({
  id: '/negociaciones',
  path: '/negociaciones',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/negociaciones.lazy').then((d) => d.Route),
)
const AppListasPreciosRoute = AppListasPreciosRouteImport.update({
  id: '/listas-precios',
  path: '/listas-precios',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/listas-precios.lazy').then((d) => d.Route),
)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboard.lazy').then((d) => d.Route),
)
const AppCostosProductosRoute = AppCostosProductosRouteImport.update({
  id: '/costos-productos',
  path: '/costos-productos',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/costos-productos.lazy').then((d) => d.Route),
)
const AppCostosOperacionalesRoute = AppCostosOperacionalesRouteImport.update({
  id: '/costos-operacionales',
  path: '/costos-operacionales',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/costos-operacionales.lazy').then((d) => d.Route),
)
const AppConfiguracionesRoute = AppConfiguracionesRouteImport.update({
  id: '/configuraciones',
  path: '/configuraciones',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculadoraRoute = AppCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/calculadora.lazy').then((d) => d.Route),
)
const AppAnalisisVentasRoute = AppAnalisisVentasRouteImport.update({
  id: '/analisis-ventas',
  path: '/analisis-ventas',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/analisis-ventas.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analisis-ventas': typeof AppAnalisisVentasRoute
  '/calculadora': typeof AppCalculadoraRoute
  '/configuraciones': typeof AppConfiguracionesRoute
  '/costos-operacionales': typeof AppCostosOperacionalesRoute
  '/costos-productos': typeof AppCostosProductosRoute
  '/dashboard': typeof AppDashboardRoute
  '/historial': typeof AppHistorialRoute
  '/listas-precios': typeof AppListasPreciosRoute
  '/negociaciones': typeof AppNegociacionesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analisis-ventas': typeof AppAnalisisVentasRoute
  '/calculadora': typeof AppCalculadoraRoute
  '/configuraciones': typeof AppConfiguracionesRoute
  '/costos-operacionales': typeof AppCostosOperacionalesRoute
  '/costos-productos': typeof AppCostosProductosRoute
  '/dashboard': typeof AppDashboardRoute
  '/historial': typeof AppHistorialRoute
  '/listas-precios': typeof AppListasPreciosRoute
  '/negociaciones': typeof AppNegociacionesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analisis-ventas': typeof AppAnalisisVentasRoute
  '/_app/calculadora': typeof AppCalculadoraRoute
  '/_app/configuraciones': typeof AppConfiguracionesRoute
  '/_app/costos-operacionales': typeof AppCostosOperacionalesRoute
  '/_app/costos-productos': typeof AppCostosProductosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/listas-precios': typeof AppListasPreciosRoute
  '/_app/negociaciones': typeof AppNegociacionesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analisis-ventas'
    | '/calculadora'
    | '/configuraciones'
    | '/costos-operacionales'
    | '/costos-productos'
    | '/dashboard'
    | '/historial'
    | '/listas-precios'
    | '/negociaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analisis-ventas'
    | '/calculadora'
    | '/configuraciones'
    | '/costos-operacionales'
    | '/costos-productos'
    | '/dashboard'
    | '/historial'
    | '/listas-precios'
    | '/negociaciones'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analisis-ventas'
    | '/_app/calculadora'
    | '/_app/configuraciones'
    | '/_app/costos-operacionales'
    | '/_app/costos-productos'
    | '/_app/dashboard'
    | '/_app/historial'
    | '/_app/listas-precios'
    | '/_app/negociaciones'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/negociaciones': {
      id: '/_app/negociaciones'
      path: '/negociaciones'
      fullPath: '/negociaciones'
      preLoaderRoute: typeof AppNegociacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listas-precios': {
      id: '/_app/listas-precios'
      path: '/listas-precios'
      fullPath: '/listas-precios'
      preLoaderRoute: typeof AppListasPreciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costos-productos': {
      id: '/_app/costos-productos'
      path: '/costos-productos'
      fullPath: '/costos-productos'
      preLoaderRoute: typeof AppCostosProductosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costos-operacionales': {
      id: '/_app/costos-operacionales'
      path: '/costos-operacionales'
      fullPath: '/costos-operacionales'
      preLoaderRoute: typeof AppCostosOperacionalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuraciones': {
      id: '/_app/configuraciones'
      path: '/configuraciones'
      fullPath: '/configuraciones'
      preLoaderRoute: typeof AppConfiguracionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculadora': {
      id: '/_app/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AppCalculadoraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analisis-ventas': {
      id: '/_app/analisis-ventas'
      path: '/analisis-ventas'
      fullPath: '/analisis-ventas'
      preLoaderRoute: typeof AppAnalisisVentasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalisisVentasRoute: typeof AppAnalisisVentasRoute
  AppCalculadoraRoute: typeof AppCalculadoraRoute
  AppConfiguracionesRoute: typeof AppConfiguracionesRoute
  AppCostosOperacionalesRoute: typeof AppCostosOperacionalesRoute
  AppCostosProductosRoute: typeof AppCostosProductosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppListasPreciosRoute: typeof AppListasPreciosRoute
  AppNegociacionesRoute: typeof AppNegociacionesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalisisVentasRoute: AppAnalisisVentasRoute,
  AppCalculadoraRoute: AppCalculadoraRoute,
  AppConfiguracionesRoute: AppConfiguracionesRoute,
  AppCostosOperacionalesRoute: AppCostosOperacionalesRoute,
  AppCostosProductosRoute: AppCostosProductosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppListasPreciosRoute: AppListasPreciosRoute,
  AppNegociacionesRoute: AppNegociacionesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
